sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  alioss:
    endpoint: your
    access-key-id: your key-id
    access-key-secret: your key-secret
    bucket-name: sky8112
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
  wechat:
    appid: your appid
    secret: your secret
    mchid: your id
    mchSerialNo: yourNo
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
