sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRHT18BPQXtFz3ekZh1
    access-key-secret: IiEy59Oe8y0XzFGkXFDF6x6SHmyRRs
    bucket-name: sky8112
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
  wechat:
    appid: wx074aa693a593e4b1
    secret: 35616687d5f935d93ad8e7f758d5e67e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://7421db15.r1.cpolar.top/wxpay/pay.php
    refundNotifyUrl: https://7421db15.r1.cpolar.top/wxpay/pay.php
